#!/bin/env bash

# MyTM Package Builder
# Builds theme packages & generates index.json

# Determine project root directory
SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

if [[ "$(basename "$PWD")" == "app" ]]; then
  PROJECT_ROOT=".."
else
  PROJECT_ROOT="."
fi

#--------------- Fallback Config ----------------

INPUT_DIR="$PROJECT_ROOT/themes"
OUTPUT_DIR="$PROJECT_ROOT/dist"
CONFIG_FILE="$PROJECT_ROOT/config.yml"
VALIDATE_ONLY=false
VALIDATE_THEME=""
TEMP_DIR="$PROJECT_ROOT/.tmp"
HASH_ALGO="sha256"
MAX_ARCHIVE_VERSIONS=10

#------------ functions ------------------

# Source utility functions
source "$SCRIPT_DIR/logging.sh"
source "$SCRIPT_DIR/.utils.sh"
source "$SCRIPT_DIR/validation.sh"

if [ -n "$XDG_CACHE_HOME" ]; then
  CACHE_DIR="$XDG_CACHE_HOME/mytm"
else
  CACHE_DIR="$HOME/.cache/mytm"
fi

show-help() {
  cat <<EOF
MyTM Theme Packager

DESC:
    Packages themes into distributable archives, generates SHA256 checksums,
    creates an index.json with metadata, and builds README.md.

USAGE:
    $0 [OPTIONS]
    $0 -vt <theme_name> [-i <input_dir>]

FLAGS:
    -h,  --help                Show this help message
    -i,  --input-dir DIR       Override input directory from config
    -o,  --output-dir DIR      Override output directory from config
    -c,  --config FILE         Set config file (default: $CONFIG_FILE)
    -vt, --validate-theme      Validate given/all theme dirs (inside input-dir)

EXAMPLE
EOF
}

cleanup() { rm -rf "$TEMP_DIR"; }


# ---------- Start script ----------

clear -x
echo -e "\n==============${NC} ${YELLOW}MyTM Packager${NC} ==============\n"

# ---------- override confs from config --------

MyTM_VERSION="NULL"
INPUT_DIR="$(get-conf "input-dir")" || exit 1
OUTPUT_DIR="$(get-conf "output-dir")" || exit 1
MAX_ARCHIVE_VERSIONS="$(get-conf "archive.max-versions")" || exit 1

#-------------- parse arguments ------------------

# Run main function if script is executed directly
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  log.fatal "This script should not be sourced."
fi

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
  -h | --help)
    show-help
    exit 0
    ;;
  -o | --output-dir)
    OUTPUT_DIR="$2"
    shift 2
    ;;
  -i | --input-dir)
    INPUT_DIR="$2"
    shift 2
    ;;
  -c | --config)
    CONFIG_FILE="$2"
    shift 2
    ;;
   -vt|--validate-theme)
    VALIDATE_ONLY=true
    if [[ -n "$2" && "$2" != -* ]]; then
      VALIDATE_THEME="$2"
      shift 2
    else
      shift 1
    fi
    ;;
  *)
    log.error "Unknown option: $1"
    show-help
    exit 1
    ;;
  esac
done


#------ Setup Environment --------

log.info -b "Checking up environment..."
log.tab.inc

req_cmds="yq jq tar awk"

has-cmd $req_cmds || { log.fatal "Please install required commands"; }
log.success "Available: $req_cmds"


if [ -d "$INPUT_DIR" ]; then
    log.success "Found Input dir: $INPUT_DIR/"
else
    log.fatal "Input directory does not exist"
fi

# Create temp dir
if [ -d "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
    log.success "Removed old Temp dir: $TEMP_DIR/"
else
    mkdir -p "$TEMP_DIR" || log.fatal "Failed to create Temp dir: $TEMP_DIR/"
    log.success "Created Temp dir"
fi

# Create output dir
if [ "$VALIDATE_ONLY" != "true" ]; then
    if [ -d "$OUTPUT_DIR" ]; then
        log.success "Output dir exists: $OUTPUT_DIR/"
    else
       if mkdir -p "$OUTPUT_DIR"; then
           log.success "Made output dir: $OUTPUT_DIR/"
       else
           log.fatal "Failed to create output or temp directory"
       fi
    fi
else
    log.info "Skipping output dir creation"
fi


#------------- Only validation check -------------

if [ "$VALIDATE_ONLY" == "true" ]; then

    log.tab.reset
    log.success -b "Environment setup complete\n"

    log.info -b "Starting Validation..."
    log.tab.inc

    validation_failed=0

    if [[ -n "$VALIDATE_THEME" ]]; then
        log.info "Validating theme: $VALIDATE_THEME"
        log.tab.inc
        if ! validate-theme-dir "$INPUT_DIR/$VALIDATE_THEME"; then
            validation_failed=1
        fi
        log.tab.dec
    else
        for theme_dir in "$INPUT_DIR"/*; do
            theme_name="$(basename "$theme_dir")"
            log.info -b "Validating theme: $theme_name"

            log.tab.inc
            if ! validate-theme-dir "$theme_dir"; then
                validation_failed=1
            fi
            log.tab.dec
            echo
        done
    fi

    log.tab.reset

    if [ "$validation_failed" -eq 1 ]; then
        log.error -b "Validation failed. Please fix the errors above."
        exit 1
    else
        log.success -b "${GREEN}Validation complete, Everything seems good.${NC}"
        exit 0
    fi
fi


# ------------ Index.json check ------------

if [ -f "${OUTPUT_DIR}/index.json" ]; then

    log.info "Found old Index"

    if rm "$OUTPUT_DIR/index.json"; then
        log.success "Removed"
    else
        log.error "Failed to remove old Index"
        log.fatal "Please remove it manually"
    fi

fi

log.info "Creating new index..."

repo_name="$(get-conf "repo.name")" || exit 1
repo_release_time="$(date +%s)"
repo_src_urls="$(get-conf -j "archive.src-urls")" || exit 1

# check if all urls contain ${{theme}} & ${{file}}
if ! echo "$repo_src_urls" | jq -e 'all( .[] ; (contains("${{theme}}") and contains("${{file}}")) )' > /dev/null; then
    log.fatal "All source URLs must contain \${{theme}} and \${{file}}."
fi

# Create index.json
jq -n \
    --arg repo_name "$repo_name" \
    --argjson release_time "$repo_release_time" \
    --argjson repo_src_urls "$repo_src_urls" \
    '{
        schema_ver: 2,
        repo_name: $repo_name,
        release: $release_time,
        src_urls: $repo_src_urls,
        themes: {}
    }' \
> "${OUTPUT_DIR}/index.json" || log.fatal "Failed to create index.json"

log.success "Done"

log.tab.reset
log.success -b "Environment setup complete\n"

#-------------- Package Themes --------------
log.info -b "Packaging themes..."
log.tab.inc

added_theme_archives=()
added_theme_count=0

# Loop through all theme dirs
for theme_dir in "${INPUT_DIR}"/*; do

    log.info "${YELLOW}Processing: $theme_dir ${NC}"
    log.tab.inc

    log.info "Validating dir.."
    log.tab.inc
    if validate-theme-dir "$theme_dir"; then
        log.tab.dec
        log.success "Directory valid"
    else
        log.tab.dec
        log.fatal "Directory Invalid. Please check"
    fi

    # Extract Theme Info
    theme_yml="$theme_dir/theme.yml"

    theme_name="$(basename "$theme_dir")" || log.fatal "Failed to extract theme name"
    theme_version="$(get-theme-ver "${theme_dir}/theme.yml")" || log.fatal "Failed to extract theme version"

    # Build archive Info
    archive_name="${theme_version}.tar.gz"
    archive_dir="${OUTPUT_DIR}/$theme_name"
    archive_path="${archive_dir}/${archive_name}"

    # Create archive directory
    mkdir -p "$archive_dir" || log.fatal "Failed to create directory: '$archive_dir'"
    log.success "Created theme directory..."


    #-------- Build theme archive ----------

    tar -czf "$archive_path" -C "$theme_dir" . || {
        log.fatal "Failed to package archive: '$theme_name'"
    }
    log.success "Packing Done"

    if [ ! -f "$archive_path" ]; then
        log.fatal "Theme archive not found: '$archive_path'"
    fi

    # Generate hash
    archive_hash="$(gen-hash "$archive_path")" || {
        log.fatal "Failed to generate hash for: '$archive_path'"
    }
    log.success "Generated $HASH_ALGO hash"


    #-------------- Update .versions.json ----------------

    versions_file="${OUTPUT_DIR}/$theme_name/.versions.json"
    jq_tmp_file="$TEMP_DIR/.versions-$theme_name.json"

    if [ ! -f "$versions_file" ]; then
        echo "[]" > "$versions_file"
    fi

    # Check if version already exists
    if jq -e --arg ver "$theme_version" 'any(.[]; .ver == $ver)' "$versions_file" > /dev/null; then
        log.success "Entry exists in versions index"
    else
        if jq --arg ver "$theme_version" \
           --arg hash "$archive_hash" \
           --arg algo "$HASH_ALGO" \
           '[ {ver: $ver, hash: {value: $hash, algo: $algo}} ] + .' \
           "$versions_file" > "$jq_tmp_file" && \
           mv "$jq_tmp_file" "$versions_file"; then
            log.success "Updated versions index"
        else
            log.fatal "Failed to update versions index"
        fi
    fi


    #-------------- Create Index Entry ----------------

    export YQI_THM="$theme_name" \
           YQI_VER="$theme_version"

    yq -i '.themes.[env(YQI_THM)].latest = env(YQI_VER)' "$OUTPUT_DIR/index.json"
    log.success "Added to Repository Index"


    # ----------- Update theme tracking ------------
    added_theme_archives+=("$archive_path")
    ((added_theme_count++))

    log.tab.dec
    log.success "${GREEN}Packaged theme: $theme_name ($theme_version)$NC\n"
done

log.tab.reset
log.success -b "${GREEN}Packaging complete${NC}\n"

# ------- cleanup -----------
log.info -b "Cleaning up..."
cleanup
log.success -b "Cleanup Complete\n"

# Show file sizes
echo -e "${BLUE}============= Summary ==============$NC\n"
show-repo-size "$OUTPUT_DIR"

if [ "$added_theme_count" -eq 0 ]; then
    echo "   No new themes added"
else
    echo -e "\n${GREEN}Themes Added: $added_theme_count$NC"
    # Group versions by theme
    declare -A theme_versions
    for archive in "${added_theme_archives[@]}"; do
        theme_name=$(basename "$(dirname "$archive")")
        version=$(basename "$archive" .tar.gz)

        if [ -z "${theme_versions[$theme_name]}" ]; then
            theme_versions[$theme_name]="$version"
        else
            theme_versions[$theme_name]="${theme_versions[$theme_name]}, $version"
        fi
    done

    for theme_name in "${!theme_versions[@]}"; do
        echo -e "   - ${BLUE}$theme_name:${NC} ${theme_versions[$theme_name]}"
    done
fi
